name: 'Find and Replace String'
description: 'Replace occurrences of given symbols in a string'
author: 'vkuksa'
inputs:
  input:
    description: 'The string you want to run this action on'
    required: true
  replace:
    description: 'A regex, that will be matched against to find a string to be replaced'
    required: true
  with:
    description: 'The string to be replaced with'
    required: true
outputs:
  value:
    description: 'The new value after find-and-replace has been run'
runs:
  using: 'node16'
  main:  'dist/index.js'